name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies with Composer
        run: composer install

      # Elimina/Comenta PHPUnit si no tienes tests
      # - name: Run PHPUnit tests
      #   run: vendor/bin/phpunit --configuration phpunit.xml

      # Elimina/Comenta Stylelint si no tienes configuración
      # - name: Install Stylelint
      #   run: npm install stylelint --save-dev

      # - name: Run Stylelint on CSS files
      #   run: npx stylelint "**/*.css"

      # Elimina/Comenta HTMLHint si no tienes configuración
      # - name: Install HTMLHint
      #   run: npm install htmlhint --save-dev

      # - name: Run HTMLHint on HTML files
      #   run: npx htmlhint "**/*.html"
