name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install dependencies with Composer
        run: composer install

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --configuration phpunit.xml

      - name: Install Stylelint
        run: npm install stylelint --save-dev

      - name: Run Stylelint on CSS files
        run: npx stylelint "**/*.css"

      - name: Install HTMLHint
        run: npm install htmlhint --save-dev

      - name: Run HTMLHint on HTML files
        run: npx htmlhint "**/*.html"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Hostinger
        run: |
          ssh u123456789@mi-dominio.com 'cd /home/u123456789/public_html && git pull origin main'
